print("assert error")

raise Exception("assert error")